### ISSUE TITLE
EC cannot be build with SDCC >= 4.5.0

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#1785]
### Component

EC firmware

### Device

NovaCustom V54 14th Gen

### Brief summary

Build fails with

```
Fails with:

src/board/system76/common/smfi.c:209: error 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
make: *** [src/arch/8051/toolchain.mk:54: build/novacustom/v540tu/2026-02-27_41e94a7/board/system76/common/smfi.rel] Error 1
Failed to build EC firmware : (2)
```

### How to reproduce

Source code: https://github.com/Dasharo/ec/pull/82/changes/c5272b5d33b563d74a1ac1c537555ddd3fb4e8c7
SDK: https://github.com/Dasharo/ec-sdk/pull/2/changes/766310cf4c03e00b346a7a6a48df1f0de006aca3

### Expected behavior

builds

### Actual behavior

errors
